ANOMALY_IQR_MULTIPLIER = 3.0
ANOMALY_MINIMUM_MARGIN = 0.05
ANOMALY_MIN_EVENTS = 100

DRIFT_WINDOW_DAYS = 7
DRIFT_THRESHOLD = 0.1
DRIFT_MIN_EVENTS = 500

CORRELATION_MIN_EVENTS = 500
CORRELATION_MIN_DAYS = 10

IDLE_MIN_DURATION_SECONDS = 60
IDLE_MAX_GAP_SECONDS = 2

MOVING_AVERAGE_WINDOW_DAYS = 7

COUNTER_RECOVERY_THRESHOLD = 100
DATA_GAP_THRESHOLD_SECONDS = 5
LLM_MODEL_NAME = "gemini-1.5-flash"
PLOT_DIR = "data/processed/plots"
